### ISSUE TITLE
Coursera Code of Conduct

### ISSUE THREAD

**Issue by jcanelhas** [Kulbear/deep-learning-coursera#13]
Isn't publishing exercise solution against coursera's honor code ?

**Comment by SantaHub** [comment]
Yes jcanelhas. Only if we copy it. Its knowledge and deserve to be shared otherwise.

**Comment by jcanelhas** [comment]
https://learner.coursera.help/hc/en-us/articles/209818863

Check the 3rd bullet point.

**Comment by AshishSardana** [comment]
This repo goes against the code-of-conduct. There's a reason why discussion forums exist for this course.

**Comment by SantaHub** [comment]
- [ ] test

**Comment by SantaHub** [comment]
https://imagebin.ca/v/3h0QSUXeZhBt
