### ISSUE TITLE
course 4 CNN when will you upload or where can we get the solution

### ISSUE THREAD

**Issue by Ayushchaurasia** [Kulbear/deep-learning-coursera#15]
Please let me know,
course 4 CNN when will you upload or where can we get the solution

**Comment by Kulbear** [comment]
No plan for quizzes on later courses (some ppl may use it to easily pass the course), there will be notebooks solutions but I could intentionally delay it.

**Comment by Ayushchaurasia** [comment]
Hi ,

Thanks for the reply.
Could you please share any help as much last day of subscription is 8... I
have read all the materials but need to complete in a time.. Otherwise I
will list this...
Please help

Thanks,
Ayush
