### ISSUE TITLE
Help Me In Understanding It.

### ISSUE THREAD

**Issue by Shivank98** [Kulbear/deep-learning-coursera#19]
Hey There,
can you make me understant about this
`Z[i, h, w, c] = conv_single_step(a_slice_prev, W[...,c], b[...,c])`
i want to know why `W[...,c]` and `b[...,c]` . i want to know why Three dots there.

In CNN step by step

**Comment by A7med01** [comment]
W[...,c] = W[:,:,:,c]
you can just write it : 
Z[i, h, w, c] = conv_single_step(a_slice_prev, W[:,:,:,c], b[:,:,:,c])
and that means all values in W at the layer c of the filter

**Comment by Shivank98** [comment]
Thanks got it
