### ISSUE TITLE
without the answers???

### ISSUE THREAD

**Issue by Adeel-Abdullah** [Kulbear/deep-learning-coursera#4]
Hey there, wonderful work! Would it be possible for you to add notebooks without the solutions as well. I really want to go through the mooc but my financial condition simply does not allow that at this point. 

I've applied on coursera for financial assistance but they take 15 days to review the application, till then I wanted to go through the material and the assignments myself, if you could help out that would be awesome!

**Comment by Kulbear** [comment]
You have full access to the programming assignment but the submission part even you are not paying for the course.

That is, you can choose the "audit" option on any course on Coursera to audit the course without any payment. 

For details about how to audit a course, see [here](https://learner.coursera.help/hc/en-us/articles/209818613-Enrollment-options).

**Comment by Adeel-Abdullah** [comment]
Thank you for your response, but auditing the course does not get you access to the programming assignments just the other course material such as the videos and the presentations; I am already auditing the course right now.

**Comment by Kulbear** [comment]
@Adeel-Abdullah I think you have the access right? But you cannot submit it, the only restriction.

**Comment by Adeel-Abdullah** [comment]
No, the assignments are not accessible either while auditing, they are accessible only once you purchase it.

**Comment by Kulbear** [comment]
@Adeel-Abdullah 
Man, you access to the assignment **HERE**
![image](https://user-images.githubusercontent.com/14886380/29808926-510b9df2-8c57-11e7-86ba-712001466e36.png)

Like the first row in my screenshot. Not the second locked one. I tested it on a free account.

EVERY Coursera programming assignment works like this. I never heard about any programming assignment that is not public.

![image](https://user-images.githubusercontent.com/14886380/29809007-a146f604-8c57-11e7-9598-29f4aee7ffc8.png)

**Comment by Adeel-Abdullah** [comment]
Apologies for the misunderstanding, I just checked. I was previously clicking on the next tab the one with the lock on it, Thankyou for the help!
