### ISSUE TITLE
Download notebooks and solutions

### ISSUE THREAD

**Issue by rs1990** [Kulbear/deep-learning-coursera#6]
Hey,

Could you tell me how you were able to download the submissions from coursera to your system?. All the folders.

Thanks.

**Comment by qiuhuaqi** [comment]
@rs1990 

Hey,

I was wondering the same thing and did a little digging.

- For IPython Notebooks: In the notebook page, go to 'File -> Download as'
- For Python utility code: In the notebook page, go to 'File -> Open...'. 
This gets you in the Jupyter server file system running on Coursera. Open the Python code you want to download and go to 'File -> Download'.

- For the SIGNS dataset: 
Go the `datasets` directory and click on the dataset files you want to download. Your browser should open a blank new tab and download the data automatically. 

I realise that this is a bit manual. But luckily there aren't many files. I test loaded a the h5py data file and it works.

Let me know if you find a better solution.
Hope this helps

**Comment by rs1990** [comment]
Hey @qiuhuaqi,

That's what I was doing but was hoping there was a better way!. 

Thanks a ton though. Will let you know if I find a better solution.

Cheers

**Comment by WesErg** [comment]
Made a new python-3 notebook and add this code to a cell. This creates a file (currdir.tar) in the current directory. Pasted the code below into the first cell and executed the cell.

Then clicked File->Open to take you to the directory listing and can download this tar file.  For the Week 4 ResNet exercise this file was around 250M.  After I downloaded it, I deleted it so it wouldn't take up room on their server. 

import os
import tarfile
tarFileName='currdir.tar'
def RecursiveFiles(dn='.',ignoreTarFile=tarFileName):
    ignore={'.pynb_checkpoints','__pycache__',ignoreTarFile}
    for dirname,subdirs,files in os.walk(dn):
        if os.path.basename(dirname) in ignore: continue
        for fn in files:
            fname=os.path.join(dirname,fn)
            yield(fname)
    return

def makeTarFile(dn='.',tfn=tarFileName):
    tar=tarfile.open(tfn,'w')
    for name in RecursiveFiles(dn,tfn):
        tar.add(name)
    tar.close()

makeTarFile()

**Comment by eduardofv** [comment]
This is a great solution. I'm reposting the code formatted, as it's important in Python.
`import os
import tarfile
tarFileName='currdir.tar'
def RecursiveFiles(dn='.',ignoreTarFile=tarFileName):
    ignore={'.pynb_checkpoints','pycache',ignoreTarFile}
    for dirname,subdirs,files in os.walk(dn):
        if os.path.basename(dirname) in ignore: continue
        for fn in files:
            fname=os.path.join(dirname,fn)
            yield(fname)
        return

def makeTarFile(dn='.',tfn=tarFileName):
    tar=tarfile.open(tfn,'w')
    for name in RecursiveFiles(dn,tfn):
        tar.add(name)
    tar.close()

makeTarFile()`

**Comment by igor-garin** [comment]
There is simpler command:
`!tar cvfz currdir.tar.gz *`

**Comment by Vadim-Stupakov** [comment]
Also you can open terminal and execute `tar cvfz currdir.tar.gz *` directly.

**Comment by ashimagarg** [comment]
Hi,

Could you please let me know how to download dataset from coursera hub? I tried downloading cat vs non-cat dataset for first assignment Logistic Regression as a Neural Network : 
From Datasets directory, I clicked on the dataset files train_catvnoncat.h5 to download. My browser opened a new tab showing error : 

1. Error! /home/jovyan/work/Week 2/Logistic Regression as a Neural Network/datasets/test_catvnoncat.h5 is not UTF-8 encoded.
2. Saving disabled.
3. See console for more details.

Thanks.

**Comment by txytju** [comment]
I tried `tar cvfz currdir.tar.gz *`.
But the images files that I downloaded couldn't be opened. Have anyone met that problem?

**Comment by overlapjho** [comment]
> tar cvfz currdir.tar.gz * 
doesn't work also in datasets they are corrupted when compressed

**Comment by davesnowdon** [comment]
You need to include the -h flag to tar so that it dereferences symbolic links. The following command in a cell works:
` !tar cvhfz currdir.tar.gz *`

**Comment by Hu-Shiqing** [comment]
It works pretty well, thanks a lot

**Comment by stavBodik** [comment]
@igor-garin and to which location it will download the files if i am browsing from chrome and using windows 10?

**Comment by igor-garin** [comment]
@stavBodik, it will not download any file but create 'currdir.tar.gz' archive in the root of the notebook. You will be able to download it later.

**Comment by stavBodik** [comment]
@igor-garin  found it already , just said some times need to explain things like that (: 
Thanks !
