### ISSUE TITLE
lr_utils not found required for load_dataset

### ISSUE THREAD

**Issue by m3kwong** [Kulbear/deep-learning-coursera#7]
Can you please provide a link on where to get this?  

Thanks

**Comment by m3kwong** [comment]
This is for the deep learning mind set assignment, thanks.

**Comment by Kulbear** [comment]
You should run the code on the Coursera platform. I didn't download those utils code and data sets from Coursera.

**Comment by shipeihg** [comment]
where can I download it ?

**Comment by toddmo** [comment]
You need to run the cell containing the imports first

**Comment by reyemarr** [comment]
Same problem here. Im trying to run the code locally; I downloaded the notebook and i'm trying to run the commands on my windows pc, but they fail because I dont have the "lr_utils" package installed.  Where can i get that package?

Thanks,
 MR

**Comment by Kulbear** [comment]
@reyemarr I recommend you run the notebook on the Coursera platform. This is not a pip package or sort of stuff, `lr_utils` are just a few functions implemented by the development team, it's accessible on the Coursera platform if you are familiar with the Jupyter notebook.

**Comment by reyemarr** [comment]
Understood. Thanks for the clarification. 
Cheers

**Comment by xiaokunx** [comment]
My guess is that the lr_utils is just a convenient class naming for "logistic regression", maybe?
 
```python
import lr_utils
help(lr_utils)
```

```
Help on module lr_utils:

NAME
    lr_utils

FUNCTIONS
    load_dataset()

FILE
    /home/jovyan/work/Week 2/Logistic Regression as a Neural Network/lr_utils.py
```

**Comment by xiaokunx** [comment]
a little more probing yield this, thanks the the trick to run bash in jupyter with a !

```sh
!cat /home/jovyan/work/Week\ 2/Logistic\ Regression\ as\ a\ Neural\ Network/lr_utils.py
```

```python
import numpy as np
import h5py
    
    
def load_dataset():
    train_dataset = h5py.File('datasets/train_catvnoncat.h5', "r")
    train_set_x_orig = np.array(train_dataset["train_set_x"][:]) # your train set features
    train_set_y_orig = np.array(train_dataset["train_set_y"][:]) # your train set labels

    test_dataset = h5py.File('datasets/test_catvnoncat.h5', "r")
    test_set_x_orig = np.array(test_dataset["test_set_x"][:]) # your test set features
    test_set_y_orig = np.array(test_dataset["test_set_y"][:]) # your test set labels

    classes = np.array(test_dataset["list_classes"][:]) # the list of classes
    
    train_set_y_orig = train_set_y_orig.reshape((1, train_set_y_orig.shape[0]))
    test_set_y_orig = test_set_y_orig.reshape((1, test_set_y_orig.shape[0]))
    
    return train_set_x_orig, train_set_y_orig, test_set_x_orig, test_set_y_orig, classes
```

**Comment by sjmodha** [comment]
can i access coursera programming assignment free. as of now it is locked

**Comment by Kulbear** [comment]
it shows locked but that lock is for submission only. you can view the material @sjmodha

**Comment by happywatermelon** [comment]
@xiaokunx hey, may i ask, how did you get the assignment downloaded to your computer and use help(lr_utils)?
i tried help(lr_utils) in the notebook and it shows:
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-1-9d87f03835f9> in <module>()
     10 
     11 
---> 12 help(lr_utils)

NameError: name 'lr_utils' is not defined

**Comment by Meghna281086** [comment]
Copy the following code in a blank text file :+1: 

import numpy as np
import h5py
    
    
def load_dataset():
    train_dataset = h5py.File('datasets/train_catvnoncat.h5', "r")
    train_set_x_orig = np.array(train_dataset["train_set_x"][:]) # your train set features
    train_set_y_orig = np.array(train_dataset["train_set_y"][:]) # your train set labels

    test_dataset = h5py.File('datasets/test_catvnoncat.h5', "r")
    test_set_x_orig = np.array(test_dataset["test_set_x"][:]) # your test set features
    test_set_y_orig = np.array(test_dataset["test_set_y"][:]) # your test set labels

    classes = np.array(test_dataset["list_classes"][:]) # the list of classes
    
    train_set_y_orig = train_set_y_orig.reshape((1, train_set_y_orig.shape[0]))
    test_set_y_orig = test_set_y_orig.reshape((1, test_set_y_orig.shape[0]))
    
    return train_set_x_orig, train_set_y_orig, test_set_x_orig, test_set_y_orig, classes

Rename the file to lr_utils.py and paste the file into your local folder "C: ...\....\Users\User"

After which run the cell. It works!!


     or

https://github.com/andersy005/deep-learning-specialization-coursera/blob/master/01-Neural-Networks-and-Deep-Learning/week2/Programming-Assignments/lr_utils.py
And paste the file into your local folder "C: ...\....\Users\User"
