### ISSUE TITLE
IN ASSIGNMENT 4 OF DEEP LEARNING AND NEURAL NETWORKS

### ISSUE THREAD

**Issue by hpaliwal4** [Kulbear/deep-learning-coursera#8]
I think There is a error in the function L_model_backward.
If it is not an error then can you tell what you did there?

**Comment by YinengXiong** [comment]
@hpaliwal4 

dW = np.dot(dZ, cache[0].T) / m
db = np.sum(dZ, axis=1, keepdims=True) / m
dA_prev = np.dot(cache[1].T, dZ)

**Comment by GaryGao829** [comment]
exactly, the db shape is not as expected
